/* eslint-disable @typescript-eslint/no-require-imports */
const { PrismaClient } = require("@prisma/client");
const prisma = new PrismaClient();
import bcrypt from 'bcrypt';


const items = [
  {
    name: "ธงประดับสัญลักษณ์พระนามาภิไธยย่อ ส.ท. ม่วง",
    img: "images/items/ธงประดับสัญลักษณ์พระนามาภิไธยย่อ ส.ท. มวง.jpg",
    status: "ปกติ",
    divisionId: 1,
    postfixId: 1,
    count: 49,
  },
  {
    name: "ธงตราสัญลักษณ์พระนามาภิไธยย่อ ส.ธ.",
    img: "images/items/ธงตราสัญลักษณ์พระนามาภิไธยย่อ ส.ธ. มวง.png",
    status: "ปกติ",
    divisionId: 1,
    postfixId: 1,
    count: 198,
  },
  {
    name: "ธงชาติไทย",
    img: "images/items/ธงชาติไทย.jpg",
    status: "ปกติ",
    divisionId: 1,
    postfixId: 1,
    count: 204,
  },
  {
    name: "ธงตราสัญลักษณ์พระปรมาภิไธยย่อ ว.ป.ร.",
    img: "images/items/ธงตราสัญลักษณ์พระปรมาภิไธยย่อ ว.ป.ร. เหลือง.png",
    status: "ปกติ",
    divisionId: 1,
    postfixId: 1,
    count: 267,
  },
  {
    name: "ธงประดับสัญลักษณ์พระนามาภิไธยย่อ ส.ก. น้ำเงิน",
    img: "images/items/ธงประดับสัญลักษณ์พระนามาภิไธยย่อ ส.ก. น้ำเงิน.png",
    status: "ปกติ",
    divisionId: 1,
    postfixId: 1,
    count: 50,
  },
  {
    name: "ธงมหาวิทยาลัยผืนใหญ่ (ขึ้นเสาธง)",
    img: "images/items/ธงมหาวิทยาลัยผืนใหญ่ (ขึ้นเสาธง).jpg",
    status: "ปกติ",
    divisionId: 2,
    postfixId: 1,
    count: 1,
  },
  {
    name: "ธงมหาวิทยาลัยผืนเล็ก",
    img: "images/items/ธงมหาวิทยาลัยผืนใหญ่ (ขึ้นเสาธง).jpg",
    status: "ปกติ",
    divisionId: 2,
    postfixId: 1,
    count: 5,
  },
  {
    name: "ธงกีฬาบัวน้ำเงินเกมส์ (แบบปัก)",
    img: "",
    status: "ปกติ",
    divisionId: 2,
    postfixId: 1,
    count: 1,
  },
  {
    name: "ธงกีฬาบัวน้ำเงินเกมส์ (แบบสกรีน)",
    img: "",
    status: "ปกติ",
    divisionId: 2,
    postfixId: 1,
    count: 1,
  },
  {
    name: "ธงชาติไทย (ขึ้นเสาธง)",
    img: "images/items/ธงชาติไทย.jpg",
    status: "ปกติ",
    divisionId: 2,
    postfixId: 1,
    count: 1,
  },
  {
    name: "ธงชาติไทย (ผืนเล็ก)",
    img: "images/items/ธงชาติไทย.jpg",
    status: "ปกติ",
    divisionId: 2,
    postfixId: 1,
    count: 7,
  },
  {
    name: "ธงสกรีนคณะบริหารธุรกิจ",
    img: "images/items/ธงสกรีนคณะบริหารธุรกิจ.jpg",
    status: "ปกติ",
    divisionId: 2,
    postfixId: 1,
    count: 4,
  },
  {
    name: "ธงสกรีนคณะศิลปกรรมศาสตร์",
    img: "images/items/ธงสกรีนคณะศิลปกรรมศาสตร์.jpg",
    status: "ปกติ",
    divisionId: 2,
    postfixId: 1,
    count: 5,
  },
  {
    name: "ธงสกรีนคณะครุศาสตร์อุตสาหกรรม",
    img: "images/items/ธงสกรีนคณะครุศาสตร์อุตสาหกรรม.jpg",
    status: "ปกติ",
    divisionId: 2,
    postfixId: 1,
    count: 4,
  },
  {
    name: "ธงสกรีนวิทยาลัยการแพทย์แผนไทย",
    img: "images/items/ธงสกรีนวิทยาลัยการแพทย์แผนไทย.jpg",
    status: "ปกติ",
    divisionId: 2,
    postfixId: 1,
    count: 4,
  },
  {
    name: "ธงสกรีนคณะวิทยาศาสตร์และเทคโนโลยี",
    img: "images/items/ธงสกรีนคณะวิทยาศาสตร์และเทคโนโลยี.jpg",
    status: "ปกติ",
    divisionId: 2,
    postfixId: 1,
    count: 5,
  },
  {
    name: "ธงสกรีนคณะเทคโนโลยีสื่อสารมวลชน",
    img: "images/items/ธงสกรีนคณะเทคโนโลยีสื่อสารมวลชน.jpg",
    status: "ปกติ",
    divisionId: 2,
    postfixId: 1,
    count: 5,
  },
  {
    name: "ธงสกรีนคณะวิศวกรรมศาสตร์",
    img: "images/items/ธงสกรีนคณะวิศวกรรมศาสตร์.jpg",
    status: "ปกติ",
    divisionId: 2,
    postfixId: 1,
    count: 5,
  },
  {
    name: "ธงสกรีนคณะสถาปัตยกรรมศาสตร์",
    img: "images/items/ธงสกรีนคณะสถาปัตยกรรมศาสตร์.jpg",
    status: "ปกติ",
    divisionId: 2,
    postfixId: 1,
    count: 5,
  },
  {
    name: "ธงสกรีนคณะเทคโนโลยีการเกษตร",
    img: "images/items/ธงสกรีนคณะเทคโนโลยีการเกษตร.jpg",
    status: "ปกติ",
    divisionId: 2,
    postfixId: 1,
    count: 5,
  },
  {
    name: "ธงสกรีนคณะเทคโนโลคหกรรมศาสตร์",
    img: "images/items/ธงสกรีนคณะเทคโนโลคหกรรมศาสตร์.jpg",
    status: "ปกติ",
    divisionId: 2,
    postfixId: 1,
    count: 5,
  },
  {
    name: "ธงสกรีนคณะศิลปศาสตร์",
    img: "images/items/ธงสกรีนคณะศิลปศาสตร์.jpg",
    status: "ปกติ",
    divisionId: 2,
    postfixId: 1,
    count: 5,
  },
  {
    name: "ธงสกรีนคณะพยาบาลศาสตร์",
    img: "images/items/ธงสกรีนคณะพยาบาลศาสตร์.jpg",
    status: "ปกติ",
    divisionId: 2,
    postfixId: 1,
    count: 2,
  },
  {
    name: "ผ้าปูโต๊ะสีฟ้า",
    img: "images/items/ผ้าปูโต๊ะสีฟ้า.jpg",
    status: "ปกติ",
    divisionId: 4,
    postfixId: 1,
    count: 20,
  },
  {
    name: "ผ้าปูโต๊ะสีเขียว",
    img: "",
    status: "ปกติ",
    divisionId: 4,
    postfixId: 1,
    count: 20,
  },
  {
    name: "พรมแดงขนห่วงไม่มีลาย (ผืนยาว) (1x10.28 เมตร)",
    img: "images/items/พรมแดงขนห่วงไม่มีลาย (ผืนยาว).jpg",
    status: "ปกติ",
    divisionId: 5,
    postfixId: 1,
    count: 1,
  },
  {
    name: "พรมแดงลูกฟูกไม่มีลาย (ผืนกว้าง) (1.98x11.48 เมตร)",
    img: "images/items/พรมแดงลูกฟูกไม่มีลาย (ผืนกว้าง).jpg",
    status: "ปกติ",
    divisionId: 5,
    postfixId: 1,
    count: 1,
  },
  {
    name: "พรมแดง มีลาย (2.09x3.07 เมตร)",
    img: "images/items/พรมสีแดง มีลาย.jpg",
    status: "ปกติ",
    divisionId: 5,
    postfixId: 1,
    count: 1,
  },
  {
    name: "พรมสีเหลือง มีลาย (2x2.94 เมตร)",
    img: "images/items/พรมสีเหลือง มีลาย.jpg",
    status: "ปกติ",
    divisionId: 5,
    postfixId: 1,
    count: 1,
  },
  {
    name: "คูลเลอร์",
    img: "images/items/คูเลอร์.jpg",
    status: "ปกติ",
    divisionId: 1,
    postfixId: 2,
    count: 20,
  },
  {
    name: "เก้าอี้หลุย",
    img: "images/items/เก้าอี้หลุย.jpg",
    status: "ปกติ",
    divisionId: 2,
    postfixId: 3,
    count: 9,
  },
  {
    name: "วอคเกอร์",
    img: "images/items/วอคเกอร์.jpg",
    status: "ปกติ",
    divisionId: 3,
    postfixId: 3,
    count: 1,
  },
  {
    name: "ลำโพงเล็ก",
    img: "images/items/ลำโพงเล็ก.jpg",
    status: "ปกติ",
    divisionId: 4,
    postfixId: 3,
    count: 2,
  },
  {
    name: "ลำโพงใหญ่",
    img: "images/items/ลำโพงใหญ่.jpg",
    status: "ปกติ",
    divisionId: 4,
    postfixId: 3,
    count: 1,
  },
  {
    name: "แท่นกราบ",
    img: "images/items/แท่นกราบ (66x70 ซม.png",
    status: "ปกติ",
    divisionId: 5,
    postfixId: 3,
    count: 1,
  },
  {
    name: "โต๊ะเคียงเก้าอี้หลุย",
    img: "images/items/โต๊ะเคียงเก้าอี้หลุย.jpg",
    status: "ปกติ",
    divisionId: 2,
    postfixId: 4,
    count: 4,
  },
  {
    name: "หีบเลือกตั้ง",
    img: "images/items/หีบเลือกตั้ง.jpg",
    status: "ปกติ",
    divisionId: 2,
    postfixId: 5,
    count: 47,
  },
  {
    name: "หีบเลือกตั้ง",
    img: "images/items/หีบเลือกตั้ง.jpg",
    status: "ปกติ",
    divisionId: 2,
    postfixId: 5,
    count: 50,
  },
  {
    name: "คูหาเลือกตั้ง",
    img: "images/items/คูหาเลือกตั้ง.jpg",
    status: "ปกติ",
    divisionId: 2,
    postfixId: 6,
    count: 60,
  },
  {
    name: "ป้ายมหาวิทยาลัย (อันใหญ่)",
    img: "images/items/ป้ายมหาวิทยาลัย (อันใหญ่).jpg",
    status: "ปกติ",
    divisionId: 2,
    postfixId: 7,
    count: 1,
  },
  {
    name: "วิลแชร์ (พับได้)",
    img: "images/items/วิลแชร์ (พับไม่ได้).jpg",
    status: "ปกติ",
    divisionId: 3,
    postfixId: 8,
    count: 11,
  },
  {
    name: "วิลแชร์ (พับไม่ได้)",
    img: "images/items/วิลแชร์ (พับไม่ได้).jpg",
    status: "ปกติ",
    divisionId: 3,
    postfixId: 8,
    count: 4,
  },
  {
    name: "ไม้ค้ำยัน ไซส์ 42 นิ้ว",
    img: "images/items/ไม้ค้ำยัน.jpg",
    status: "ปกติ",
    divisionId: 3,
    postfixId: 9,
    count: 1,
  },
  {
    name: "ไม้ค้ำยัน ไซส์ 46 กว้าง 18 ซม. สูง 113-121 ซม. (เหมาะสำหรับส่วนสูง 135-144 ซม.)",
    img: "images/items/ไม้ค้ำยัน.jpg",
    status: "ปกติ",
    divisionId: 3,
    postfixId: 9,
    count: 3,
  },
  {
    name: "ไม้ค้ำยัน ไซส์ 48 กว้าง 18 ซม. สูง 118-126 ซม. (เหมาะสำหรับส่วนสูง 145-154 ซม.)",
    img: "images/items/ไม้ค้ำยัน.jpg",
    status: "ปกติ",
    divisionId: 3,
    postfixId: 9,
    count: 2,
  },
  {
    name: "ไม้ค้ำยัน ไซส์ 50 กว้าง 18 ซม. สูง 123-131 ซม. (เหมาะสำหรับส่วนสูง 155-164 ซม.)",
    img: "images/items/ไม้ค้ำยัน.jpg",
    status: "ปกติ",
    divisionId: 3,
    postfixId: 9,
    count: 5,
  },
  {
    name: "ไม้ค้ำยัน ไซส์ 52 กว้าง 18 ซม. สูง 128-136 ซม. (เหมาะสำหรับส่วนสูง 165-174 ซม.)",
    img: "images/items/ไม้ค้ำยัน.jpg",
    status: "ปกติ",
    divisionId: 3,
    postfixId: 9,
    count: 5,
  },
  {
    name: "ไม้เท้าหัวฆ้อน 3 ขา",
    img: "images/items/ไม้เท้าหัวฆ้อน 3 ขา.jpg",
    status: "ปกติ",
    divisionId: 3,
    postfixId: 9,
    count: 1,
  },
  {
    name: "ไม้เท้าก้านร่ม",
    img: "images/items/ไม้เท้าก้านร่ม.jpg",
    status: "ปกติ",
    divisionId: 3,
    postfixId: 9,
    count: 3,
  },
  {
    name: "ไม้เท้าขาเดียวค้ำข้อศอก",
    img: "images/items/ไม้เท้าขาเดียวค้ำข้อศอก.jpg",
    status: "ปกติ",
    divisionId: 3,
    postfixId: 9,
    count: 1,
  },
  {
    name: "โรลอัพ 2.28*1.5 เมตร",
    img: "",
    status: "ปกติ",
    divisionId: 3,
    postfixId: 9,
    count: 1,
  },
  {
    name: "ขาตั้งตาลปัตร",
    img: "images/items/ขาตั้งตาลปัตร.jpg",
    status: "ปกติ",
    divisionId: 5,
    postfixId: 9,
    count: 10,
  },
  {
    name: "เชิงเทียนชนวน",
    img: "images/items/เชิงเทียนชนวน.jpg",
    status: "ปกติ",
    divisionId: 5,
    postfixId: 9,
    count: 1,
  },
  {
    name: "แบนเนอร์ 3*2.28 เมตร",
    img: "",
    status: "ปกติ",
    divisionId: 4,
    postfixId: 10,
    count: 1,
  },
  {
    name: "ฟลิปชาร์ต",
    img: "images/items/ฟลิปชาร์ต.jpg",
    status: "ปกติ",
    divisionId: 4,
    postfixId: 10,
    count: 3,
  },
  {
    name: "เครื่องบันทึกเสียง (DSS)",
    img: "images/items/เครื่องบันทึกเสียง (DSS).jpg",
    status: "ปกติ",
    divisionId: 4,
    postfixId: 11,
    count: 1,
  },
  {
    name: "เครื่องขยายภาพ สำหรับผู้พิการสายตา",
    img: "images/items/เครื่องขยายภาพ สำหรับผู้พิการสายตา.png",
    status: "ปกติ",
    divisionId: 4,
    postfixId: 11,
    count: 1,
  },
  {
    name: "หัวลากวิลแชร์",
    img: "images/items/หัวลากวิลแชร์.jpg",
    status: "ปกติ",
    divisionId: 4,
    postfixId: 12,
    count: 1,
  },
  {
    name: "กระธางธูปทองเหลือง",
    img: "images/items/กระถางธูปทองเหลือง.jpg",
    status: "ปกติ",
    divisionId: 5,
    postfixId: 13,
    count: 1,
  },
  {
    name: "กระถางธูปปูนปั้นสีขาว",
    img: "images/items/กระถางธูป ปูนปั้นสีขาว.jpg",
    status: "ปกติ",
    divisionId: 5,
    postfixId: 13,
    count: 1,
  },
  {
    name: "ขันโตกไม้ (ใหญ่)",
    img: "images/items/ขันโตกไม้ (ใหญ่).jpg",
    status: "ปกติ",
    divisionId: 5,
    postfixId: 13,
    count: 1,
  },
  {
    name: "ขันโตกไม้ (กลาง)",
    img: "images/items/ขันโตกไม้ (กลาง).jpg",
    status: "ปกติ",
    divisionId: 5,
    postfixId: 13,
    count: 2,
  },
  {
    name: "ขันน้ำมนต์พร้อมพานรอง",
    img: "images/items/ขันน้ำมนต์พร้อมพานรอง.jpg",
    status: "ปกติ",
    divisionId: 5,
    postfixId: 13,
    count: 1,
  },
  {
    name: "เบาะรองนั่งสีเขียว สำหรับอาสนะสงฆ์",
    img: "images/items/เบาะรองนั่งสีเขียว สำหรับอาสนะสงฆ์ (62x64 ซม.png",
    status: "ปกติ",
    divisionId: 5,
    postfixId: 13,
    count: 10,
  },
  {
    name: "เบาะรองนั่งสีทองลายกุหลาบ สำหรับอาสนะสงฆ์",
    img: "images/items/เบาะรองนั่งสีทองลายกุหลาบ สำหรบอาสนะสงฆ์ (55x55 ซม.png",
    status: "ปกติ",
    divisionId: 5,
    postfixId: 13,
    count: 20,
  },
  {
    name: "เครื่องนมัสการทองน้อย",
    img: "images/items/เครื่องนมัสการทองน้อย (29x43 ซม.).png",
    status: "ปกติ",
    divisionId: 5,
    postfixId: 14,
    count: 1,
  },
  {
    name: "พานธูปเทียนแพสีม่วง",
    img: "images/items/พานธูปเทียนแพสีม่วง (34x62 ซม.png",
    status: "ปกติ",
    divisionId: 5,
    postfixId: 14,
    count: 3,
  },
  {
    name: "พานธูปเทียนแพสีเหลือง",
    img: "images/items/พานธูปเทียนแพสีเหลือง (34x62 ซม.png",
    status: "ปกติ",
    divisionId: 5,
    postfixId: 14,
    count: 1,
  },
  {
    name: "พานธูปเทียนแพสีฟ้า",
    img: "",
    status: "ปกติ",
    divisionId: 5,
    postfixId: 14,
    count: 1,
  },
  {
    name: "พานแว่นฟ้า",
    img: "images/items/พานแว่นฟ้า.jpg",
    status: "ปกติ",
    divisionId: 5,
    postfixId: 14,
    count: 1,
  },
  {
    name: "เชิงเทียนทองเหลือง",
    img: "images/items/เชิงเทียนทองเหลือง.jpg",
    status: "ปกติ",
    divisionId: 5,
    postfixId: 15,
    count: 2,
  },
  {
    name: "เชิงเทียนปูนปั้นสีขาว",
    img: "images/items/เชิงเทียนปูนปั้นสีขาว.jpg",
    status: "ปกติ",
    divisionId: 5,
    postfixId: 15,
    count: 1,
  },
  {
    name: "พุ่มเงินทอง พานแก้ว",
    img: "images/items/พุ่มเงินทอง พานแก้ว (35x76 ซม.png",
    status: "ปกติ",
    divisionId: 5,
    postfixId: 15,
    count: 1,
  },
  {
    name: "พุ่มเงินทอง (ใหญ่)",
    img: "images/items/พุ่มเงิน พุ่มทอง (ผ้า) No.6 (22x61 ซม.png",
    status: "ปกติ",
    divisionId: 5,
    postfixId: 15,
    count: 1,
  },
  {
    name: "พุ่มเงินทอง",
    img: "images/items/พุ่มเงิน พุ่มทอง (ผ้า) No.6 (22x61 ซม.png",
    status: "ปกติ",
    divisionId: 5,
    postfixId: 15,
    count: 6,
  },
  {
    name: "พุ่มดอกไม้สีขาว",
    img: "images/items/พุ่มดอกไม้สีขาว (30x64 ซม.png",
    status: "ปกติ",
    divisionId: 5,
    postfixId: 15,
    count: 1,
  },
  {
    name: "พุ่มดอกไม้สีฟ้า",
    img: "images/items/พุ่มดอกไม้สีฟ้า (25x76 ซม.png",
    status: "ปกติ",
    divisionId: 5,
    postfixId: 15,
    count: 1,
  },
  {
    name: "พุ่มดอกกุหลาบสีฟ้า",
    img: "images/items/พุ่มดอกไม้สีฟ้า (45x60 ซม.png",
    status: "ปกติ",
    divisionId: 5,
    postfixId: 15,
    count: 1,
  },
  {
    name: "พุ่มดอกไม้ สีม่วง1",
    img: "images/items/พุ่มดอกไม้สีม่วง 1 (23x58 ซม.png",
    status: "ปกติ",
    divisionId: 5,
    postfixId: 15,
    count: 1,
  },
  {
    name: "พุ่มดอกไม้ สีม่วง2",
    img: "images/items/พุ่มดอกไม้สีม่วง 2 26x79.png",
    status: "ปกติ",
    divisionId: 5,
    postfixId: 15,
    count: 1,
  },
  {
    name: "พุ่มดอกไม้ สีม่วง3",
    img: "images/items/พุ่มดอกไม้สีม่วง 3 28x79.png",
    status: "ปกติ",
    divisionId: 5,
    postfixId: 15,
    count: 1,
  },
  {
    name: "พุ่มดอกไม้ สีม่วง4",
    img: "images/items/พุ่มดอกไม้สีม่วง 4 (34x72 ซม.png",
    status: "ปกติ",
    divisionId: 5,
    postfixId: 15,
    count: 1,
  },
  {
    name: "พุ่มดอกกุหลาบสีม่วง",
    img: "images/items/พุ่มดอกกุหลาบสีม่วง 45x60.png",
    status: "ปกติ",
    divisionId: 5,
    postfixId: 15,
    count: 1,
  },
  {
    name: "พุ่มดอกไม้สีเหลือง",
    img: "images/items/พุ่มดอกไม้สีเหลือง 25x79.png",
    status: "ปกติ",
    divisionId: 5,
    postfixId: 15,
    count: 2,
  },
  {
    name: "ตาลปัตร",
    img: "images/items/ตาลปัตร.jpg",
    status: "ปกติ",
    divisionId: 5,
    postfixId: 16,
    count: 10,
  },
  {
    name: "ไม้พรมน้ำมนต์",
    img: "images/items/ไม้พรมน้ำมนต์.jpg",
    status: "ปกติ",
    divisionId: 5,
    postfixId: 17,
    count: 1,
  },
  {
    name: "บายศรีต้น",
    img: "images/items/บายศรีต้น.jpg",
    status: "ปกติ",
    divisionId: 5,
    postfixId: 18,
    count: 1,
  },
  {
    name: "ภาชนะกรวดน้ำ",
    img: "images/items/ภาชนะกรวดน้ำ.jpg",
    status: "ปกติ",
    divisionId: 5,
    postfixId: 20,
    count: 1,
  },
  {
    name: "สายสิญจน์",
    img: "images/items/สายสิญจ์.jpg",
    status: "ปกติ",
    divisionId: 5,
    postfixId: 19,
    count: 1,
  },
  {
    name: "อาสนะสงฆ์แบบมีพนักพิงสีแดง",
    img: "images/items/อาสนะสงฆ์ (พนักพิง) สีแดง.jpg",
    status: "ปกติ",
    divisionId: 5,
    postfixId: 20,
    count: 10,
  },
  {
    name: "อาสนะสงฆ์แบบมีพนักพิงสีเหลือง",
    img: "images/items/อาสนะสงฆ์ (พนักพิง) สีเหลือง.jpg",
    status: "ปกติ",
    divisionId: 5,
    postfixId: 20,
    count: 10,
  },
  {
    name: "พระฉายาลักษณ์สมเด็จพระบรมราช ชนนีพันปีหลวง (ใหญ่) 1.48x2.66 เมตร",
    img: "images/items/พระฉายาลักษณ์สมเด็จพระบรมราช ชนนีพันปีหลวง (ใหญ่).jpg",
    status: "ปกติ",
    divisionId: 5,
    postfixId: 21,
    count: 1,
  },
  {
    name: "พระบรมฉายาลักษณ์ พระบาทสมเด็จพระมหาภูมิพลอดุลยเดชมหาราช บรมนาถบพิตร (ใหญ่) 1.36x2.54 เมตร",
    img: "images/items/พระบรมฉายาลักษณ์ พระบาทสมเด็จพระมหาภูมิพลอดุลย(ใหญ่).jpg",
    status: "ปกติ",
    divisionId: 5,
    postfixId: 21,
    count: 1,
  },
  {
    name: "พระบรมฉายาลักษณ์ พระบาทสมเด็จพระมหาภูมิพลอดุลยเดชมหาราช บรมนาถบพิตร กรอบทอง 60.5x86 ซม.",
    img: "images/items/พระบรมฉายาลักษณ์ พระบาทสมเด็จพระมหาภูมิพลอดุลยกรอบทอง.jpg",
    status: "ปกติ",
    divisionId: 5,
    postfixId: 21,
    count: 1,
  },
  {
    name: "พระบรมฉายาลักษณ์ พระบาทสมเด็จพระมหาภูมิพลอดุลยเดชมหาราช บรมนาถบพิตร กรอบลาย 59x84 ซม.",
    img: "images/items/พระบรมฉายาลักษณ์ พระบาทสมเด็จพระมหาภูมิพลอดุลยเดชมหาราชกรอบลาย.jpg",
    status: "ปกติ",
    divisionId: 5,
    postfixId: 21,
    count: 1,
  },
  {
    name: "พระฉายาลักษณ์สมเด็จพระนางเจ้า ฯ พระบรมราชินี กรอบทอง 60x85 ซม.",
    img: "images/items/พระฉายาลักษณ์สมเด็จพระนางเจ้า ฯ พระบรมราชินี กรอบทอง.jpg",
    status: "ปกติ",
    divisionId: 5,
    postfixId: 21,
    count: 1,
  },
  {
    name: "พระฉายาลักษณ์สมเด็จพระนางเจ้า ฯ พระบรมราชินี กรอบลาย 90x115 ซม.",
    img: "images/items/พระฉายาลักษณ์สมเด็จพระนางเจ้า ฯ พระบรมราชินี กรอบลาย.jpg",
    status: "ปกติ",
    divisionId: 5,
    postfixId: 21,
    count: 1,
  },
  {
    name: "พระฉายาลักษณ์สมเด็จพระกนิษฐาธิราชเจ้ากรมสมเด็จพระเทพรัตนราชสุดา ฯ สยามบรมราชกุมารี กรอบทอง 60.5x86 ซม.",
    img: "images/items/พระฉายาลักษณ์สมเด็จพระกนิษฐาธิราชเจ้ากรมสมเด็จพระเทพรัตนราชสุดา_ทอง.png",
    status: "ปกติ",
    divisionId: 5,
    postfixId: 21,
    count: 1,
  },
  {
    name: "พระฉายาลักษณ์สมเด็จพระกนิษฐาธิราชเจ้ากรมสมเด็จพระเทพรัตนราชสุดา ฯ สยามบรมราชกุมารี กรอบลาย 71x81.5 ซม.",
    img: "images/items/พระฉายาลักษณ์สมเด็จพระกนิษฐาธิราชเจ้ากรมสมเด็จพระเทพรัตนราชสุดา_ลาย.png",
    status: "ปกติ",
    divisionId: 5,
    postfixId: 21,
    count: 1,
  },
  {
    name: "พระฉายาลักษณ์สมเด็จพระเจ้าลูกเธอเจ้าฟ้าพัชรกิติยาภา ฯ กรอบทอง 67x92 ซม.",
    img: "images/items/พระฉายาลักษณ์สมเด็จพระเจ้าลูกเธอเจ้าฟ้าพัชรกิติยาภา ฯ กรอบทอง.jpg",
    status: "ปกติ",
    divisionId: 5,
    postfixId: 21,
    count: 1,
  },
  {
    name: "พระฉายาลักษณ์สมเด็จพระเจ้าลูกเธอเจ้าฟ้าพัชรกิติยาภา ฯ กรอบลาย 65x91 ซม.",
    img: "images/items/พระฉายาลักษณ์สมเด็จพระเจ้าลูกเธอเจ้าฟ้าพัชรกิติยาภา ฯ กรอบลาย.jpg",
    status: "ปกติ",
    divisionId: 5,
    postfixId: 21,
    count: 1,
  },
  {
    name: "พระบรมฉายาลักษณ์ ร.10 คู่พระบรมราชินี 1.40x2.62 เมตร",
    img: "images/items/พระบรมฉายาลักษณ์ ร.10 คู่พระบรมราชินี.png",
    status: "ปกติ",
    divisionId: 5,
    postfixId: 21,
    count: 1,
  },
  {
    name: "พระรูปสมเด็จพระอริยวงศาคตญาณ สมเด็จพระสังฆราชสกลมหาสังฆปริณายก 66.5x92 เมตร",
    img: "images/items/พระรูปสมเด็จพระอริยวงศาคตญาณ สมเด็จพระสังฆราชสกลมหาสังฆปริณายก.jpg",
    status: "ปกติ",
    divisionId: 5,
    postfixId: 22,
    count: 1,
  },
  {
    name: "หมอนอิง",
    img: "images/items/หมอนอิง 40x40.png",
    status: "ปกติ",
    divisionId: 5,
    postfixId: 12,
    count: 1,
  },
  {
    name: "กระโถน",
    img: "images/items/กระโถน.jpg",
    status: "ปกติ",
    divisionId: 5,
    postfixId: 12,
    count: 1,
  },
  {
    name: "ขันเงินขนาดเล็ก (6x3.5 ซม.)",
    img: "images/items/ขันเงินขนาดเล็ก.jpg",
    status: "ปกติ",
    divisionId: 5,
    postfixId: 12,
    count: 1,
  },
  {
    name: "วิลแชร์ไฟฟ้า",
    img: "images/items/วิลแชร์ไฟฟ้า.jpg",
    status: "ปกติ",
    divisionId: 4,
    postfixId: 8,
    count: 1,
  },
  {
    name: "พระฉายาลักษณ์ พระบาทสมเด็จพระวชิรเกล้าเจ้าอยู่หัว (ใหญ่) 1.53x2.70 เมตร",
    img: "images/items/พระฉายาลักษณ์ พระบาทสมเด็จพระวชิรเกล้าเจ้าอยู่หัว (ใหญ่).jpg",
    status: "ปกติ",
    divisionId: 5,
    postfixId: 21,
    count: 1,
  },
  {
    name: "พุ่ม 5 ยอด",
    img: "images/items/พุ่ม 5 ยอด (23x78 ซม.png",
    status: "ปกติ",
    divisionId: 5,
    postfixId: 15,
    count: 1,
  },
];

const main = async () => {
  const hashedPassword = await bcrypt.hash('1234', 9);
  await prisma.user.create({
    data: {
      name: "SuperAd",
      lastname: "Admin",
      gender: "ชาย",
      tel: "0653675098",
      email: "your841209@gmail.com",
      username: "admin67891",
      password: hashedPassword,
      role: "admin",
    },
  });

  await prisma.imgAndVideoPreview.createMany({
    data: [
      { name: "images/1,737,183,947,9441,736,238,327,129re3.mkv", type: 2 },
      { name: "images/1,739,162,066,878banner.jpg", type: 1 },
      { name: "images/1,739,162,075,964banner.jpg", type: 0 },
    ],
  });

  await prisma.division.createMany({
    data: [
      { name: "ฝ่ายบริหารงานทั่วไป" },
      { name: "ฝ่ายพัฒนาศักยภาพนักศึกษา" },
      { name: "ฝ่ายสุขภาพและอนามัย" },
      { name: "ฝ่ายแนะแนวการศึกษาอาชีพและศิษย์เก่า" },
      { name: "ฝ่ายทำนุบำรุงศิลปวัฒนธรรม" },
    ],
  });

  await prisma.set.createMany({
    data: [
      {
        name: "อุปกรณ์พิธีสงฆ์",
      },
      {
        name: "อุปกรณ์พิธีมุทิตาจิต (รดน้ำ)",
      },
      {
        name: "พานพุ่ม",
      },
      {
        name: "พระฉายาลักษณ์",
      },
      {
        name: "พรม",
      },
    ],
  });

  await prisma.postfix.createMany({
    data: [
      { name: "ผืน" },
      { name: "ถัง" },
      { name: "ตัว" },
      { name: "ชุด" },
      { name: "หีบ" },
      { name: "คูหา" },
      { name: "ป้าย" },
      { name: "คัน" },
      { name: "อัน" },
      { name: "แผ่น" },
      { name: "เครื่อง" },
      { name: "หัว" },
      { name: "ใบ" },
      { name: "พาน" },
      { name: "คู่" },
      { name: "เล่ม" },
      { name: "ด้าม" },
      { name: "ต้น" },
      { name: "ม้วน" },
      { name: "ที่" },
      { name: "องค์" },
      { name: "พระรูป" },
    ],
  });

  await prisma.origanization.createMany({
    data: [
      { name: "คณะวิศวกรรมศาสตร์ (วศ.)", group: 1 },
      { name: "คณะบริหารธุรกิจ (บธ.)", group: 1 },
      { name: "คณะเทคโนโลยีคหกรรมศาสตร์ (ทค.)", group: 1 },
      { name: "คณะศิลปกรรมศาสตร์ (ศก.)", group: 1 },
      { name: "คณะเทคโนโลยีการเกษตร (ทก.)", group: 1 },
      { name: "คณะครุศาสตร์อุตสาหกรรม (คอ.)", group: 1 },
      { name: "คณะสถาปัตยกรรมศาสตร์ (สถ.)", group: 1 },
      { name: "คณะวิทยาศาสตร์และเทคโนโลยี (วท.)", group: 1 },
      { name: "คณะเทคโนโลยีสื่อสารมวลชน (ทสม.)", group: 1 },
      { name: "คณะเทคโนโลยีสื่อสารมวลชน (ทสม.)", group: 1 },
      { name: "คณะการแพทย์บูรณาการ (กพบ.)", group: 1 },
      { name: "คณะพยาบาลศาสตร์", group: 1 },
      { name: "กองกลาง", group: 0 },
      { name: "กองอาคารสถานที่", group: 0 },
      { name: "กองนโยบายและแผน", group: 0 },
      { name: "กองบริหารงานบุคคล", group: 0 },
      { name: "กองคลัง", group: 0 },
      { name: "กองประชาสัมพันธ์", group: 0 },
      { name: "กองกฏหมาย", group: 0 },
      { name: "กองยุทธศาสตร์ต่างประเทศ", group: 0 },
      { name: "กองส่งเสริมสุขภาพและกีฬา", group: 0 },
      { name: "สำนักส่งเสริมวิชาการและงานทะเบียน", group: 0 },
      { name: "สำนักวิทยบริการและเทคโนโลยีสารสนเทศ", group: 0 },
      { name: "สำนักประกันคุณภาพการศึกษา", group: 0 },
      { name: "สำนักสหกิจศึกษา", group: 0 },
      { name: "สำนักวิจัยและพัฒนา", group: 0 },
      { name: "สำนักจัดการทรัพย์สิน", group: 0 },
      { name: "สำนักบัณฑิตศึกษา", group: 0 },
      { name: "สำนักความร่วมมืออุตสากรรม", group: 0 },
      { name: "สถานีวิทยุกระจายเสียง", group: 0 },
      { name: "สำนักงานอธิการบดี", group: 0 },
      { name: "สหกรณ์ มทร.", group: 0 },
      { name: "กองพัฒนานักศึกษา", group: 0 },
    ],
  });

  const dataToInsert = items.flatMap((item) =>
    Array.from({ length: item.count }, () => ({
      name: item.name,
      img: item.img,
      status: item.status,
      divisionId: item.divisionId,
      postfixId: item.postfixId,
    }))
  );

  await prisma.items.createMany({
    data: dataToInsert,
  });
};

main()
  .then(async () => {
    await prisma.$disconnect();
  })
  .catch(async (e) => {
    console.error(e);
    await prisma.$disconnect();
    process.exit(1);
  });
